spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_wisdom?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: sff
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iflytek.petwisdombackend.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 8080

aliyun:
  api-key: sk-521e7a669f2c4e0e8870be34067cb2d1

file:
  upload:
    path: D:/uploads/videos/